FROM node:20-alpine

#the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose port 3000 (default for many frontend apps)
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
